server:
  port: 8000

spring:
  application:
    name: springclound-eureka-provider

eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
